# New ports collection makefile for:	php5-phar
# Date created:			23 Nov 2011
# Whom:				Oleg Pudeyev <oleg@bsdpower.com>
#
# $FreeBSD$
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-phar

.include "${MASTERDIR}/Makefile"
